### PR TITLE
Moodle gradebook scoring

### PR DESCRIPTION
**Pull request by jimbedgar**
Could a setting be added to the Moodle plug-in that allows the developer to select which score is saved in the gradebook when a user makes multiple attempts, e.g. Highest score, Last score, First score, etc.
Thanks.

### CODE REVIEW

**Comment by thomasmars** [comment]
Please make the pull request target the 'master' branch

**Comment by akaskens** [comment]
I agree with the pull request from jimbedgar. Please allow a setting so that in Moodle, we can determine whether the scorebook records the first score, best score or most recent scroe. The way it is now, it defaults to accepting the most recent score. So everytime a learner tries the course presentation activity (and clicks on the final summary slide), his/her grade gets replaced with the most recent score in the gradebook. Learners get discouraged (as they may have got 100% the first time, but only 10% the second time because they didn't wan to redo all the activities in the presentation) and teacher has no idea what score the learner got (as gradebook records the most recent score). I posted about this in the H5P forum, but am posting here to support jimbedgar's pull request. Thank you so much!!

**Comment by thomasmars** [comment]
I agree, that would be nice. It is impossible to diff and accept this pull request when it is forked from 'master' and targeted at 'stable' though. Please re-target the pull request to target the 'master' branch ( https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/ ) before we can proceed, thanks.

**Comment by akaskens** [comment]
Thank you for responding thomasmars! It looks like the original pull request (by jimbedgar) was moved today - Hopefully, the request is now in the correct place??? If it is not, can you let me know? thank you.

**Comment by thomasmars** [comment]
Hi, you're now creating a pull request from 'master' into a new branch 'HFP-1841-Add-reporting-OEQ'.
You should be creating a pull request from your fork to this repository's 'master' branch. Right now there is 94 commits in this pull request, mostly consisting of commits already existing on our 'master', which makes it impossible to merge this pull request in.

If you look at the top of your pull request it says the following:
`jimbedgar wants to merge 94 commits into HFP-1841-Add-reporting-OEQ from master`
It should look something like:
`name wants to merge 1 commit into h5p:master from myfork:master`
like for instance this pull request does: https://github.com/h5p/h5p-moodle-plugin/pull/210

**Comment by akaskens** [comment]
hello thomasmars, can you tell me if this pull request was successfully moved to target the "master branch"? I did not make the original request and I don't understand how to change to where it is supposed to go. However, we are at a crossroads with continuing to use H5P in our many Moodle courses, because learners keep asking us about the scoring issue (they want the Moodle score to represent their best score, when they have multiple tries at the course presentation). But currently, in the H5P plugin for Moodle, we cannot specify "first score, or best score" we really want to continue using H5P because it is fantastic!! But we'd love to see these options for recording scores in the Moodle gradebook. awaiting your response, and thank you!!!

**Pull request closed without merging**
