### PR TITLE
New module_view, module_list_view & xAPI events

### PR DESCRIPTION
**Pull request by nadavkav**
Patch to solve issues: #69 & #45

### CODE REVIEW

**Comment by thomasmars** [comment]
The Activity Report (course admin -> reports -> activity report) seems to get a lot more views than it should, seems it gets a view for each xAPI event fired, this is probably not the intended behaviour ?

**Comment by thomasmars** [comment]
Everything else looks great! :+1:  If we can resolve this, I will merge it in

**Comment by falcon-git** [comment]
I don't think the view report should be based on xAPI at all. Can't it get an event whenever an H5P page is rendered?

**Comment by nadavkav** [comment]
Weird, I am not getting redundant view events. Only when I open an hvp/view.php page.
(I have that event fires only at one point, the view page)

**Comment by nadavkav** [comment]
Please hold integration, as I made some data manipulation on the event action name after the event was fired. which is breaking the hvp log report.

I am taking the following off the code:
```
protected function validate_data() {
        $this->data['action'] .= '_' . $this->data['other']->data->statement->verb->display->{'en-US'};
}
```
And devising a new way to indicate the "verb" in the logstore table

**Comment by nadavkav** [comment]
New PR https://github.com/h5p/h5p-moodle-plugin/pull/87 , replacing this one.

**Comment by nadavkav** [comment]
New PR #88 , replacing this one.

**Pull request closed without merging**
