### PR TITLE
finnish translation

### PR DESCRIPTION
**Pull request by Jarvil**
finnish translation

### CODE REVIEW

**Comment by thomasmars** [comment]
@fnoks Please don't merge in directly to stable.
@Jarvil Please make pull requests to the 'master' branch, instead of 'stable. Also translations should be done through the Moodle AMOS translation interface, ref: https://docs.moodle.org/dev/Translating_plugins

**Comment by Jarvil** [comment]
@thomasmars you can only translate few lines through AMOS, most of it you can only translate here in Github

**Comment by thomasmars** [comment]
Every string that is in use within our plugin (in the Moodle plugin) and defined in https://github.com/h5p/h5p-moodle-plugin/blob/stable/lang/en/hvp.php should be translatable through AMOS. If you're sure that something is only translatable through Github, please point me to it and I'll have a look.

**Comment by Jarvil** [comment]
Hello,

There might have been misunderstanding, the basic plugin information can be translated through AMOS but not f.ex. course presentation or any other libraries texts, that needs to be done here in github

**Comment by germanvaleroelizondo** [comment]
Read Moodle Docs at https://docs.moodle.org/dev/Translating_plugins#H5P_plugin and add/remove/change as needed.

**Pull request merged**
