### PR TITLE
Fix missing encode_content_links on backup_hvp_activity_task.class

### PR DESCRIPTION
**Pull request by nadavkav**
Was unable to backup activity and was also breaking full course backup,
if user was using hvp activity in course.

Patch, fixes above issue.

### CODE REVIEW

**Comment by nadavkav** [comment]
@icc , FYI This is very important!

**Comment by icc** [comment]
Indeed, thank you!

**Comment by juho-jaakkola** [comment]
This affects the backup despite not having the actual backup steps defined?

**Comment by nadavkav** [comment]
You should at least pull in #41 before pulling this one.

**Comment by icc** [comment]
Ok, I'm sorry I though this was something that was broken with the current backup support? I can move it into a separate branch.

**Comment by juho-jaakkola** [comment]
I think it's fine if #41 is rebased on this, and then merged. The backup feature isn't yet completely finished, but it's fine to merge it as long as the `FEATURE_BACKUP_MOODLE2` value is kept `false` so that no-one accidentally makes a backup using an incomplete implementation.

**Comment by nadavkav** [comment]
I agree with @juho-jaakkola

**Comment by nadavkav** [comment]
Sorry I was not clear in the beginning (as I thought #41 was already merged)

**Pull request merged**
