### PR TITLE
Add more info about the install process

### PR DESCRIPTION
**Pull request by nadavkav**
To make it more clear to those who are not familiar with inter-project code and library dependencies.
"Copy the entire https://github.com/h5p/h5p-php-library code into /moodle/mod/hvp/library"

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
Easier to just include the direct git command. E.g. http://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

**Comment by nadavkav** [comment]
You are completely correct. but there are other cases too...
I came up with the need for making the readme more clear after two Moodle administrators (not developers who do not know git) clicked the Download button and installed the H5P module as is.
And it did not work, until I add the "missing" library to the proper place.

Please see if you can improve the readme to include several install scenarios, as not everyone is a developer ;-)

btw, h5p is an amazing framework!!! looking forward to add something to it

**Comment by stumari** [comment]
Install process is quite clear, and nadavkav's suggestion could make it even clear. Yet, on a different note, does h5p moodle source code requires v. 3991875 of h5p library? Or one can use the most recent one with it?
P.S. Truly, h5p is really an amazing framework and thanks a lot for developing a module for Moodle. The latter may not have as many installations as WordPress but will have nearly as many as Joomla or Drupal, when the use of In-Video Quizzes is concerned, other h5p functionality, not to mention.

**Comment by icc** [comment]
Indeed, the installation process is a bit unclear. I've updated the readme and added some more info.

**Pull request merged**
