### PR TITLE
Issue #238

### PR DESCRIPTION
**Pull request by imarichev**
Move $PAGE->set_url() higher to prevent "this page did not call $PAGE->set_url()" notice

### CODE REVIEW

**Comment by thomasmars** [comment]
@fnoks I'm not able to reproduce the error he is describing.

**Comment by fnoks** [comment]
@thomasmars Have you set up your environment to display PHP notices?

**Comment by thomasmars** [comment]
@fnoks Yes, are you able to reproduce this ?

**Comment by thomasmars** [comment]
I'm not able to reproduce this. Please re-open the issue with detailed steps to reproduce this if it is still happening.

**Pull request closed without merging**
