### PR TITLE
Adding german translation

### PR DESCRIPTION
**Pull request by udduk**
I have added a german translation of the strings. But I'm not completely sure if it is the correct path?

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
The path seems to be correct.

It would be nice if you could squash the three commits into a single one, and give it a more descriptive commit message. "Create hvp.php" doesn't really say anything about what has been changed and why, whereas e.g. "Adds German translations" immediately describes what the commit is about.

See e.g. http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by udduk** [comment]
Ok, thank you. I will open a new pull request for that.

**Comment by juho-jaakkola** [comment]
A good to know tip: If you have access to command line, you don't necessarily have to replace a PR (pull request) with another when you make changes. It is also possible to simply update existing PRs:

```sh
# Make changes to the commits (e.g. squash or rename):
git rebase -i
# Push the updated version to the existing PR:
git push -f origin <branch name>
```

**Comment by udduk** [comment]
Ah, i didn't know that. It would have been way easier that way. I'll use it next time :)
Thanks a lot!

**Pull request closed without merging**
